### ISSUE TITLE
清单文件冲突，建议把清单文件去掉

### ISSUE THREAD

**Issue by mrchenmo** [qiangxi/CheckUpdateLibrary#1]

**Comment by qiangxi** [comment]
我已经在我们公司的多个项目中使用这个库了,并没有出现清单文件冲突的情况啊,请问具体是哪里冲突了呢?
在进行编译的时候,gradle会自动把每个依赖中的manifest文件合并为一个,有这个清单文件的话,就不用另外再配置DownloadService了.

**Comment by mrchenmo** [comment]
android:allowBackup="false"这个属性两个值得设置不一样，编译会不通过。

**Comment by mrchenmo** [comment]
android:allowBackup="false"这个属性两个值得设置不一样，编译会不通过。

**Comment by mrchenmo** [comment]
还要在自己项目的清单文件里面加上一句话才能编译通过。

**Comment by qiangxi** [comment]
已经删掉了manifest.xml文件中的相关配置,并且已经更新library,你可以试试最新的1.0.5版本.谢谢你的建议!!!

**Comment by qiangxi** [comment]
不过,你需要自己在manifest.xml中配置相关权限和DownloadService了,配置方式请参见readme.

**Comment by mrchenmo** [comment]
还有个问题 dialog 的问题，最好不要使用this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND, 这代码让背景变暗，这样会导致一个问题，在手机屏幕刚刚熄灭的时候立即解锁屏幕，会导致暗背景消失。最好是在布局中添加一层阴影，当然这只是个建议。

**Comment by qiangxi** [comment]
好建议!!!这是个历史遗留问题,确实存在,但是可以通过自定义Dialog来自定义布局进而避免该问题,
将来会考虑使用DialogFragment替代Dialog,到时会把这个问题考虑进去,不过短时间内如果没有比较严重的bug可能不会更新library.万分感谢!
