### ISSUE TITLE
exitButton 的 bug

### ISSUE THREAD

**Issue by mcxinyu** [qiangxi/CheckUpdateLibrary#12]
`private void initEvent() {
        exitApp.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ((Activity) context).finish();
                System.exit(0);
            }
        });
        ...
}`

这里的结束方式有问题，一般别人的 update activity 都不是栈中的第一个 activity，这种结束方式会导致 app 回到上一个 activity，而不是结束 app。

**Comment by qiangxi** [comment]
你好,你说的是强制更新方式吧,我们来思考一下:如果一个app需要强制更新,说明不更新的话,app是没法用的,对于这种业务,正确的做法应该是在app的启动页或主页就应该展示出这个对话框,强制用户去下载最新版本,否则就退出应用,而不是把检测更新放到某个子功能下面,让用户主动去触发,如果用户不主动触发更新,那岂不是可以依然使用老版本?
所以正确情况下,强制更新的对话框应该在启动页或主页中展示,采用

((Activity) context).finish(); 
System.exit(0);

是没有问题的哦.

如果还有其他疑问,欢迎再次提出.

**Comment by mcxinyu** [comment]
好。我的 app 有读取存储的权限，为什么点击了更新按钮却没有反应呢？

**Comment by qiangxi** [comment]
你好,
1. 首先你使用的是最新版本的library吗?当前library最新的版本为1.1.0.老版本的library确实存在这个问题,新版本中已经修复了.
2. 如果你使用的是最新的版本,那么请确认是否配置好了FileProvider呢?配置方式见readme.

**Comment by qiangxi** [comment]
还有如果你的app适配到Android 6.0,那么需要动态获取读写权限哦?获取方式同样参考readme.

**Comment by mcxinyu** [comment]
都有配置。

**Comment by qiangxi** [comment]
请问是点击没反应还是点击之后提示什么消息了吗?比如下载失败之类的

**Comment by mcxinyu** [comment]
点击之后没有任何效果，连logcat都没有。

**Comment by qiangxi** [comment]
你好,
在华为和小米的6.0手机上都跑了几遍,没有发现点击没反应的问题,所以还请你再仔细检查一下代码,看看配置是否正确以及使用的是否是最新的library.
如果可以的话,你也可以换个其他机型测试.
如果确实配置无误以及library确实是最新的,且仍然出现这种问题的话,我会尽可能找到和你机型匹配的测试机去测试.

**Comment by mcxinyu** [comment]
`private void initEvent() {
        ...
        forceUpdate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //先比较主项目的targetSdkVersion,如果>=23,进行下一步,否则直接下载
                if (context.getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.M) {
                    //如果项目运行在6.0+设备中,进行权限动态获取,否则直接下载
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                        int permissionStatus = ActivityCompat.checkSelfPermission(context, Manifest.permission_group.STORAGE);
                        if (permissionStatus != PackageManager.PERMISSION_GRANTED) {
                            ActivityCompat.requestPermissions((Activity) context, new String[]{Manifest.permission.
                                    WRITE_EXTERNAL_STORAGE}, FORCE_UPDATE_DIALOG_PERMISSION_REQUEST_CODE);
                        }
                    } else {
                        download();
                    }
                } else {
                    download();
                }
            }
        });
    }`

这里的 `ActivityCompat.checkSelfPermission(context, Manifest.permission_group.STORAGE);`
在 Fragment 中申请权限，不要使用 ActivityCompat.requestPermissions, 直接使用 Fragment 的 requestPermissions 方法，否则会回调到 Activity 的 onRequestPermissionsResult。

**Comment by qiangxi** [comment]
你好,
首先,对于回调到 Activity 的 onRequestPermissionsResult,如果Fragment想接收的话,可以通过在Fragment中定义一个方法,把Activity中的回调转到Fragment中去操作.
另外.我看到你的PR了,请问你这种解决方式能解决这个问题吗?如果可以的话,我就merge了.

**Comment by mcxinyu** [comment]
我测试了，可以解决在 fragment 中的权限请求回调。当然，activity 中的 onRequestPermissionsResult 需要删掉。

**Comment by qiangxi** [comment]
我的意思是:比如在Activity中请求会回调Activity 的 onRequestPermissionsResult,在Fragment中请求会回调Fragment 的 onRequestPermissionsResult,

**Comment by mcxinyu** [comment]
可以的，我提供了一个构造函数在 fragment 中使用，只要使用这个构造函数就可以在 fragment 中调用权限请求回调。

public UpdateDialog(Context context, @NonNull Fragment fragment) {
}

**Comment by qiangxi** [comment]
已merge,谢谢你的PR.
明天我会发布新版本.
谢谢!!!

**Comment by mcxinyu** [comment]
你可以加点注释，使用的用户就更清楚了。
