### ISSUE TITLE
我把里面有关权限申请的代码都去掉 targetApi 25,在6.0,7.0好像也运行正常

### ISSUE THREAD

**Issue by weilixing00** [qiangxi/CheckUpdateLibrary#16]
另外，能不能留个qq什么的，交流下。

**Comment by qiangxi** [comment]
使用我发布的library可以;把项目down下来自己定义用也可以,2种方式只要能完成功能都ok啦.
这是我的qq:981787371,加的时候请注明"Android交流"哈.
