### ISSUE TITLE
无法引用库呢

### ISSUE THREAD

**Issue by mcxinyu** [qiangxi/CheckUpdateLibrary#17]
compile 'com.qiangxi.checkupdatelibrary:checkupdatelibrary:1.1.1'

Error:(111, 13) Failed to resolve: com.qiangxi.checkupdatelibrary:checkupdatelibrary:1.1.1

**Comment by qiangxi** [comment]
在目前的1.1.1和1.1.2版本需要使用如下方式引用哦:
compile 'com.qiangxi.checkupdatelibrary:checkupdatelibrary:1.1.2@aar'
