### ISSUE TITLE
Error:(1246) Attribute "progress_text_size" has already been defined

### ISSUE THREAD

**Issue by Destiny01** [qiangxi/CheckUpdateLibrary#2]
添加你的库之后报错
![222](https://cloud.githubusercontent.com/assets/11342391/20334013/c3768bfa-abf1-11e6-95a9-f137d3edf240.png)

**Comment by qiangxi** [comment]
这是因为attr属性命名冲突,CheckUpdateLibrary中关于进度条的自定义属性命名就是采用这种命名方式,你看看你自己的项目中定义的attr是否有和CheckUpdateLibrary中冲突的,然后把这些冲突的命名修改成不一样的就ok了,

**Comment by Destiny01** [comment]
ok解决了，跟别的三方库冲突了，谢谢！

**Comment by qiangxi** [comment]
别客气,一起进步!
