### ISSUE TITLE
通知栏不显示下载进度问题

### ISSUE THREAD

**Issue by chaychan** [qiangxi/CheckUpdateLibrary#20]
您好，我用的是华为荣耀8，安卓7.0非强制更新只是显示正在后台下载的吐司，通知栏没有进度显示，而且后续没有操作了。

**Comment by qiangxi** [comment]
你好,根据你的描述,考虑到有以下几种情况:
1. 没有按照readme进行相关配置,导致没有进行下载,即代码没有走到弹出通知的那一步.
2.下载地址有问题并且设备禁用了通知显示,如果设备禁用了通知显示,即便代码写了弹出通知,但通知栏仍然不会有显示的,再加上如果下载地址有问题,也不会提示下载失败.
如果以上都不是,那么还请描述一下具体的情况,看看有没有错误日志,有的话一并发上来看看.如果是library中的问题,我会尽快修复!

**Comment by chaychan** [comment]
README还有哪些没有配置？我该配的都配了，而且设备有给予通知权限，强制更新没问题，可是非强制更新就不行，我刚用了7.0的模拟器再测一次，也不行，说明并不是设备的问题，而是你的代码的确存在问题，希望你可以调试下。

**Comment by qiangxi** [comment]
你好,我使用7.0的模拟器测试之后,一切正常啊,我运行的是library的demo,你可以使用demo跑一遍看看.
在项目中进行集成时,请按照readme进行相关配置.并且确保使用的library是最新的.
因为我这边不能复现你的问题,也不知道你的代码是如何编写的,所以如果可以的话,你可以把项目整个down下来,然后进行相关调试,看看是哪里出的问题.
我也会尽量找到华为荣耀8这种机型进行相关测试.谢谢!!!

**Comment by chaychan** [comment]
不好意思，清单文件忘记配置DownloadService,现在是可以了，但是通知栏里的通知却无法清除，一直显示在那里，下载完成，点击安装，清除不了，安装完也还在。

**Comment by qiangxi** [comment]
通知不能轻易被清除是代码强制指定的,这么做主要是考虑到如果是个普通通知,用户不小心清除之后就再也找不到安装的入口了.所以不让轻易清除.  
- 但是你还是可以清除的,不同的设备可能会有不同的操作,比如左滑或者右滑就可以删除,只不过会弹出对话框让你确定是否删除这个通知.
- 或者你可以继承BaseService 自己实现通知弹出的逻辑,就像Library中的DownloadService 一样.NotificationUtil的每个方法的最后一个参数就是指定弹出的通知是否可被清除的.

**Comment by chaychan** [comment]
觉得安装完应该去除掉通知才对
