### ISSUE TITLE
我想自定义弹窗的样式咋办？好像没有提供方法，要我自己用moudle的方式添加到项目中在更改吗？

### ISSUE THREAD

**Issue by mrchenmo** [qiangxi/CheckUpdateLibrary#22]

**Comment by qiangxi** [comment]
你好，两种方式：
1. 就是你说的，把library下载下来，然后修改library源码。这种方式方便快捷，但是如果以后library升级，你用的还是之前老版本的代码，就体验不了新版本的特性了。
2. 直接定义一个全新的Dialog，样式以及动画等完全可以自定义。这种方式更自由，但是需要你自己添加相关逻辑，比如要继承library中的BaseService用于下载，android 6.0的权限判断和申请，更新内容的展示等等。可以参考readme和library中自带的两种Dialog的逻辑去自定义你自己的Dialog。

**Comment by mrchenmo** [comment]
@qiangxi 我看到了谢谢，还有，哥们你强制更新和非强制更新用的全是一个请求码FORCE_UPDATE_DIALOG_PERMISSION_REQUEST_CODE，这个定义都没用到

**Comment by qiangxi** [comment]
你好，你用的不是最新的lib吧，请使用最新的1.1.3版本。

**Comment by mrchenmo** [comment]
你看看demo里面，除非你的demo不是最新的，要不然就是我看错

**Comment by qiangxi** [comment]
你好，首先demo是最新的，请求码也没用重复；其次demo仅仅是示例而已，更重要的是lib，毕竟lib才是开发者真正集成到项目中使用的，在老版本的lib中请求码确实使用重复了，但是在随后的版本中修复了这个bug，所以我建议你使用最新的lib。

**Comment by mrchenmo** [comment]
@qiangxi 嗯，我看到了，因为之前就是以Moudle的模式引入的，所以能不能麻烦您把demo的lib更新一下呢？

**Comment by mrchenmo** [comment]
@qiangxi 我对比了，1.1.3和demo中的代码差别不大，您要是觉得麻烦，我自行改就行。谢谢

**Comment by qiangxi** [comment]
.......，github上不管demo还是lib都已经是最新的代码了，你只需要把项目重新down一份，然后使用新的lib替换掉旧的lib即可；当然你也可以自己修改一下。^_^

**Comment by mrchenmo** [comment]
@qiangxi github demo里面的lib代码不是新的，所以我才会有上面的疑问？麻烦您看下，我刚才对比了
