### ISSUE TITLE
exception 信息被吞了？

### ISSUE THREAD

**Issue by mcxinyu** [qiangxi/CheckUpdateLibrary#24]
app 下载失败至少把 log 打印出来啊？

**Comment by qiangxi** [comment]
Hi ，lib中所有的下载失败，接口请求失败都会捕获异常，然后在对应的回调里面回调出去，可以在回调中打断点dbug查看失败原因。打log的功能目前没有，不过以后更新会加上，tks！

**Comment by mcxinyu** [comment]
建议加一个方法修改一个内置变量 showLog，true 的话就把 log 打印出来。

**Comment by qiangxi** [comment]
ok
