### ISSUE TITLE
ForceUpdateDialog.java强制更新时权限判断返回码变量写错了

### ISSUE THREAD

**Issue by BLiYing** [qiangxi/CheckUpdateLibrary#25]
public static final int FORCE_UPDATE_DIALOG_PERMISSION_REQUEST_CODE = 1;//权限请求码没用上，还是用的UPDATE_DIALOG_PERMISSION_REQUEST_CODE = 0；

**Comment by qiangxi** [comment]
hi，你用的不是最新版的lib吧，这个问题早已经修复了，用最新lib试试吧

**Comment by BLiYing** [comment]
我是直接从你这个github仓库clone的代码

**Comment by qiangxi** [comment]
呃,这个问题我已经知道了[#27](https://github.com/qiangxi/CheckUpdateLibrary/issues/27)
