### ISSUE TITLE
存储权限判断有些多余

### ISSUE THREAD

**Issue by BLiYing** [qiangxi/CheckUpdateLibrary#26]
public String CreatFile() {
        File tempPath = new File(MainActivity.this.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "apk");//外部存储路径
        if (!tempPath.exists()) {//创建目录
            try {
                tempPath.mkdir();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return tempPath.getPath();
    }
使用MainActivity.this.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "apk"的内部存储的方式创建路径则不需要获取存储权限，这样在android6.0以上机型还省去了动态权限获取。你的Environment.getExternalStorageDirectory().getPath()这种方式则需要获取权限。

**Comment by qiangxi** [comment]
really?抽空我研究一下，可以的话，在下一版优化一波
