### ISSUE TITLE
gradle 安装出错

### ISSUE THREAD

**Issue by jacobcyl** [qiangxi/CheckUpdateLibrary#30]
\app\build\intermediates\exploded-aar\com.qiangxi.checkupdatelibrary\checkupdatelibrary\1.1.3\res\layout\checkupdatelibrary_force_update_dialog_layout.xml

Error:(105, 37) No resource found that matches the given name (at 'background' with value '?attr/selectableItemBackground').

**Comment by qiangxi** [comment]
使用以前的lib的话是会出现这个问题，原因是你APP的主题没有使用Compat主题，切换成compat主题就好了。不过这个问题在目前最新的lib中已经修改了，不会再遇到了。你可以下载lib试试看~
