### ISSUE TITLE
更新下载的时候是单线程下载？

### ISSUE THREAD

**Issue by lyxc** [qiangxi/CheckUpdateLibrary#31]
如题，在提示有更新时，更新下载模块，是单线程下载还是多线程下载？

**Comment by qiangxi** [comment]
您好，是单线程下载。之前编码时，不止考虑过这个情况，还考虑过要不要做断点续传，但最后都选择不做，因为这个库的核心功能就是检查并下载更新，用多线程下载以及断点续传没有太大必要。

**Comment by lyxc** [comment]
哦。我们这边遇到的问题是，在移动4G网络下，下载特别慢，甚至失败的情况。
