### ISSUE TITLE
大神你好  为什么我看你的demo

### ISSUE THREAD

**Issue by 317056658** [qiangxi/CheckUpdateLibrary#33]
import com.qiangxi.checkupdatelibrary.callback.StringCallback;
import com.qiangxi.checkupdatelibrary.imageloader.ImageLoader;
  这两个接口不可以现实

**Comment by 317056658** [comment]
你还有Demo  我真心不懂，误导别人啊

**Comment by qiangxi** [comment]
您好，两个接口都可以实现啊，能把代码切出来看看吗？

**Comment by 317056658** [comment]
我是真的现实不了 Q.debug()  这个方法也没有用！！！

**Comment by 317056658** [comment]
这两个接口 你确定你的库里面有？

**Comment by qiangxi** [comment]
呃，你是不是使用的旧的lib，但是又参考的新的sample？

**Comment by 317056658** [comment]
compile 'com.qiangxi.checkupdatelibrary:checkupdatelibrary:1.1.3@aar'    参考了你的sample   你介绍说不懂，就看你的sample  - -！

**Comment by qiangxi** [comment]
果然是这样。。。你用的是旧的lib，但是我的sample已经更新了。你可以下载目前最新的lib重新试下~

**Comment by 317056658** [comment]
请麻烦更新你的资料

**Comment by qiangxi** [comment]
呃，请问更新什么资料？你是说README吗？目前README就是针对目前最新的代码的啊，如果你想查看旧的lib的README，请点击[1.1.3版本的README](https://github.com/qiangxi/CheckUpdateLibrary/blob/master/1.1.3%E5%8F%8A%E4%B9%8B%E5%89%8D%E7%89%88%E6%9C%AC%E7%9A%84Readme.md)，如果想查看旧的lib的代码，请点击[1.1.3版本的项目代码](https://github.com/qiangxi/CheckUpdateLibrary/tree/83b84bce468f53cef925b5cc3c8a37d74a6f4777)

**Comment by 317056658** [comment]
是的  谢谢 。但是好像你并没有介绍你的最新sample 的用法

**Comment by 317056658** [comment]
最新的sample 用法 什么时候出啊？

**Comment by qiangxi** [comment]
呃，这个不是在最新的readme中说了嘛~~~~

**Comment by 317056658** [comment]
我怎么没有发现  实现那两个接口的方法 - -！
