### ISSUE TITLE
你好大神！！为什么我自定义普通更新启动不了服务？

### ISSUE THREAD

**Issue by 317056658** [qiangxi/CheckUpdateLibrary#34]
你好大神！！为什么我自定义普通更新启动不了服务？  我的系统是5.1的

**Comment by 317056658** [comment]
StrictMode: file:// Uri exposed through Intent.getData()
                                                                               java.lang.Throwable: file:// Uri exposed through Intent.getData()  严苛模式下 总报 不能暴露地址， 我的是5.1的系统。

**Comment by qiangxi** [comment]
方便把代码贴出来吗，这样太抽象了，不是太理解

**Comment by 317056658** [comment]
public class AppDownloadService extends BaseService {
    private int iconResId;
    private String appName;
    private Intent mIntent;
    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Log.d("启动了服务", "onStartCommand: ");
        if (null == intent) {
            return START_NOT_STICKY;
        }
        mIntent = intent;
        appName = intent.getStringExtra("appName");
        iconResId = intent.getIntExtra("iconResId", -1);
        if (iconResId == -1) {
            iconResId = R.drawable.icon_downloading;
        }
        Log.d("启动了服务", "onStartCommand: ");
        download(intent.getStringExtra("downloadUrl"), intent.getStringExtra("filePath"), intent.getStringExtra("fileName"), true);
        return super.onStartCommand(intent, flags, startId);
    }

    @Override
    public void downloading(int currentProgress, int totalProgress) {
        Log.d("正在下载", "downloading: ");
        NotificationUtil.showDownloadingNotification(this, currentProgress, totalProgress, iconResId, appName, false);
    }
    //下载成功
    @Override
    public void downloadSuccess(File file) {
        Log.d("下载成功！", "downloading: "+Build.VERSION.SDK_INT);

        NotificationUtil.showDownloadSuccessNotification(this, file, iconResId, appName, "下载完成,点击安装", false);
    }

    //下载失败
    @Override
    public void downloadFailure(String s) {
        Log.d("下载失败！", "downloading: ");
        NotificationUtil.showDownloadFailureNotification(this, mIntent, iconResId, appName, "下载失败,点击重新下载", true);
    }
}

**Comment by 317056658** [comment]
下次成功后调用知道工具类  报了一个异常StrictMode: file:// Uri exposed through Intent.getData()
java.lang.Throwable: file:// Uri exposed through Intent.getData() 严苛模式下报异常 不能暴露地址， 我的是5.1的系统。

**Comment by qiangxi** [comment]
从你贴的代码上看不出什么问题。
但是从异常原因以及系统版本来看，你的测试机是不是开启了严格模式了？如果开启请关掉。
如果没开启，请使用目前最新的lib再试试看？

**Comment by 317056658** [comment]
开启了  不能解决这个解决吗？  我在代码里面也开了严苛模式
