### ISSUE TITLE
不支持高版本

### ISSUE THREAD

**Issue by JanRisun** [qiangxi/CheckUpdateLibrary#37]
环境 Android studio 3.1.1
gradle 4.4 ，gradle插件版本3.1.1
compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.qiangxi.sample"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
立即更新无响应

**Comment by qiangxi** [comment]
你好，我这边已经把相关的版本升级到目前最新的了，没有发现你说的问题。不过我修复了lib中的一个逻辑判断bug，该bug可能会导致已经授予过权限后再次点击立即更新会出现无响应，所以你可以把最新的lib拉取下来再做尝试看看？

**Comment by JanRisun** [comment]
赞！
