### ISSUE TITLE
打包编译不通过！！！

### ISSUE THREAD

**Issue by lihuanming** [qiangxi/CheckUpdateLibrary#39]
Error:注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: F:\AndroidProject\2.0\meicool_v2\CheckUpdateLib\src\main\java\com\qiangxi\checkupdatelibrary\task\BaseTask.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
FAILURE: Build failed with an exception.

* What went wrong:
Could not read entry ':app:transformClassesWithDexBuilderForToutiaoRelease' from cache taskHistory.bin (F:\AndroidProject\2.0\meicool_v2\.gradle\4.4\taskHistory\taskHistory.bin).
> java.io.IOException: 数据错误(循环冗余检查)。

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 18s

**Comment by qiangxi** [comment]
你好，从贴出的日志看不出有什么问题，请使用 ` gradlew build -d -i `命令查看更多日志信息，再贴上来看看？
