### ISSUE TITLE
aosp_hammerhead 这个机型会报空指针

### ISSUE THREAD

**Issue by lihuanming** [qiangxi/CheckUpdateLibrary#40]
java.lang.NullPointerException

Attempt to invoke virtual method 'java.lang.String com.qiangxi.checkupdatelibrary.CheckUpdateOption.getNewAppUrl()' on a null object reference

 java.lang.RuntimeException:Unable to start service com.qiangxi.checkupdatelibrary.service.DownloadService@c03407e with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=/com.qiangxi.checkupdatelibrary.service.DownloadService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.qiangxi.checkupdatelibrary.CheckUpdateOption.getNewAppUrl()' on a null object reference
--

**Comment by qiangxi** [comment]
你好，请贴出完成的stacktrace
