### ISSUE TITLE
【bug】io异常后，仍然会走success回调。

### ISSUE THREAD

**Issue by PasserC** [qiangxi/CheckUpdateLibrary#43]
DownloadRequest.class

@Override
    public void request() {
        CallbackDispatcher.dispatchRequestStart(mCallback);
        OkHttpClient client = new OkHttpClient();
        //构建Request
        Request request = new Request.Builder().url(mUrl).build();
        //发起请求
        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                L.e(e);
                CallbackDispatcher.dispatchRequestFailure(mCallback, e);
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) throws IOException {
                L.e(response.toString());
                final ResponseBody body = response.body();
                if (body == null) {
                    CallbackDispatcher.dispatchRequestFailure(mCallback, new DownloadException("body==null"));
                    return;
                }
                writeFileFromBody(mApk, body);
                CallbackDispatcher.dispatchDownloadSuccess(mCallback, mApk);
                CallbackDispatcher.dispatchRequestFinish(mCallback);
            }
        });
    }

 /**
     * 从响应体中获取InputStream并写入文件，在写入过程中获取下载进度并回调
     *
     * @param file apk 文件
     * @param body 响应体
     * @throws IOException io过程中的异常
     */
    private void writeFileFromBody(File file, ResponseBody body) throws IOException {
        final InputStream is = body.byteStream();
        final long totalLength = body.contentLength();
        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream(file);
            final byte data[] = new byte[2048];
            int len;
            long current = 0;
            while ((len = is.read(data)) != -1) {
                fos.write(data, 0, len);
                current += len;
                //1s回调一次
                if (current < totalLength)
                    if (System.currentTimeMillis() - mLastUpdateTime < 1000) continue;
                mLastUpdateTime = System.currentTimeMillis();
                CallbackDispatcher.dispatchDownloading(mCallback, current, totalLength);
            }
            fos.flush();
        } catch (IOException e) {
            L.e(e);
            CallbackDispatcher.dispatchRequestFailure(mCallback, new DownloadException(e));
        } finally {
            if (is != null) is.close();
            if (fos != null) fos.close();
        }
    }

**Comment by qiangxi** [comment]
已fix，请拉取最新代码试试看~
