### ISSUE TITLE
显示更新的UpdateDialog可否增加一些判断？

### ISSUE THREAD

**Issue by 13930203940** [qiangxi/CheckUpdateLibrary#5]
当后台返回的数据，没有dialog需要填写的数据多的时候，比如：服务器没有返回发布时间，更新内容等等，这样UpdateDialog在相应的位置上面，就会显示null。这样对于扩展性不是很好。可以在UpdateDialog 的initData()；方法里面增加一些空值判断，如果使用者没有设置，就将该条目隐藏。当然通过直接导入你的库然后再去重写，会实现这个功能，但是通过添加依赖的方式，是不能够直接重新你的源码的，希望这个问题，你可以解决。

**Comment by qiangxi** [comment]
good,说实话,这个问题在发布第一版的时候就发现了,但是当时由于公司项目需要这些字段,所以不存在为空的情况,所以就没加判断,现在这个问题终于被你发现了.
对于这个问题的解决,你可以从git上down一份源码,然后把这个问题修改好之后,提交一个PR给我,我会merge你的PR,然后release一个新版.
或者我自己修改好,然后release一个新版,但是恐怕要等一段时间以后了,现在公司项目赶的紧,一些工作要在年前割接完毕,忙的要死,还请谅解哈~~

**Comment by qiangxi** [comment]
CheckUpdateLibrary已经更新到[1.0.7](https://github.com/qiangxi/CheckUpdateLibrary)啦,对你说的情况进行了优化,去试试看合你意不?
