### ISSUE TITLE
CheckUpdateInfo实体字段为空

### ISSUE THREAD

**Issue by walorwang** [qiangxi/CheckUpdateLibrary#6]
CheckUpdateInfo实体字段为空时，加判断：自动隐藏弹出对话框条目

**Comment by qiangxi** [comment]
你这个问题和[#5](https://github.com/qiangxi/CheckUpdateLibrary/issues/5)一样,可以看一下那个问题的回答,还请见谅

**Comment by qiangxi** [comment]
CheckUpdateLibrary已经更新到[1.0.7](https://github.com/qiangxi/CheckUpdateLibrary)啦,对你说的情况进行了优化,去试试看合你意不?
