### ISSUE TITLE
android7.0

### ISSUE THREAD

**Issue by songsongtao** [qiangxi/CheckUpdateLibrary#8]
android.os.FileUriExposedException: file:///storage/emulated/0/checkupdatelib/syw.apk exposed beyond app through Intent.getData()
android7.0下载完成安装报错

**Comment by qiangxi** [comment]
Android7.0对于文件操作这一块采用了“严格模式”，主要是为了保护用户隐藏，当时这个库还未考虑兼容7.0，所以在7.0上安装app会报这个错，既然如此，我会在近期修复这个问题并发布一个新版本。谢谢！！！

**Comment by qiangxi** [comment]
你可以试试新版[v1.0.8](https://github.com/qiangxi/CheckUpdateLibrary),对7.0安装报错bug进行了修复
